### PR TITLE
Issues raised by reyes

### PR DESCRIPTION
**Pull request by mburridge**
Fixes to broken links as per https://github.com/frontity/api-reference/issues/69

### CODE REVIEW

**Review by juanmaguitar — APPROVED** [review]

**Review by rmartinezduque — COMMENTED** [review]
@mburridge Everything looks good to me. I have only noticed that there are practically no punctuation marks (periods at the end of the sentences) in the comscore-analytics.md page. My only suggestion would be reviewing this if possible before merging the changes.

**Comment by mburridge** [comment]
Well spotted @rmartinezduque , I've added punctuation as appropriate.

**Comment by mburridge** [comment]
While doing the punctuation, as requested by Reyes above, I took the opportunity to review the whole document and have made some changes to the text.

**Review by rmartinezduque — APPROVED** [review]
Looks great, thanks @mburridge.

**Review by juanmaguitar — APPROVED** [review]

**Pull request merged**
